name = "discord-interactions-router"
main = "worker.ts"
compatibility_date = "2024-11-01"

[[queues.producers]]
binding = "INTERACTION_QUEUE"
queue = "discord-interactions"

[[kv_namespaces]]
binding = "VPS_STATUS"
id = "3b68fb5b35fa4cd2ad37689bf70302f3"